# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPMYWar286cYiamDJ1WuzWqD2C_Usiq8
"""

from flask import Flask, render_template, request
import numpy as np
import os
import pickle

app = Flask(__name__)
filename = 'RFC_model.pkl'
model = pickle.load(open(filename, 'rb'))

@app.route('/')
def index():
  return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
        SessionsPerWeek = request.form.get("SessionsPerWeek")
        AvgSessionDurationMinutes = request.form.get("AvgSessionDurationMinutes")
        PlayerLevel = request.form.get("PlayerLevel")
        AchievementsUnlocked = request.form.get("AchievementsUnlocked")
        features = [
            float(SessionsPerWeek),
            float(AvgSessionDurationMinutes),
            float(PlayerLevel),
            float(AchievementsUnlocked)]
        prediction = model.predict([features])[0]
        if prediction == 1:
            prediction = "low"
        if prediction == 2:
            prediction = "medium"
        if prediction == 3:
            prediction = "high"
        return render_template("index.html", prediction=prediction)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)