apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaming-app-deployment
  labels:
    app: gaming-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gaming-app
  template:
    metadata:
      labels:
        app: gaming-app
    spec:
      containers:
      - name: gaming-app-container
        image: lindseylevander/gaming0:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gaming-app-service
spec:
  type: NodePort
  selector:
    app: gaming-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

